# DATA CLEANSING [POPULI CENTER'S SURVEY]

Sumber Data dalam proyek ini adalah hasil survey nasional dari Lembaga Populi Center pada Bulan Juni 2023.

# TAHAP 1: MENGIMPOR LIBRARY DAN MEMBACA DATABASE

In [ ]:
# IMPORT NEEDED LIBRARY
import pandas as pd

In [ ]:
#LOADING DATA
df_surnas = pd.read_excel("/content/drive/MyDrive/surnas juni 2023.xlsx")

#CHECKING THE DATA
df_surnas = pd.DataFrame(df_surnas)

#MENGOPI DATAFRAME
df_surnas_copied = df_surnas.copy()
df_surnas_copied.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Columns: 252 entries, NO to P105
dtypes: int64(183), object(69)
memory usage: 2.5+ MB

# TAHAP 2: DATA CLEANING

# A. Kesesuaian nomor kuesioner dengan jenis kelamin

In [ ]:
#Mengecek (GANJIL)(LAKI-LAKI)

#Mengecek apakah ada nomor kuesioner ganjil yang berjenis kelamin perempuan
gender_1 = df_surnas_copied[(df_surnas_copied['NO KUISIONER'] % 2 != 0) & (df_surnas_copied['JENIS KELAMIN'] == 'Perempuan')]

gender_1.loc[:, ['NO KUISIONER', 'JENIS KELAMIN']]
#Ada 4 data yang tidak sesuai yakni nomor kuisioner: 107, 109, 1047, 1169

      NO KUISIONER JENIS KELAMIN
100            107     Perempuan
102            109     Perempuan
1010          1047     Perempuan
1126          1169     Perempuan

In [ ]:
#Jika ingin MENGUBAH jenis kelaminnya menjadi laki-laki

#Buat daftar index dari sel yang ingin diubah
ix_gender_1 = [100, 102, 1010, 1126]

#Buat iterasi untuk menampung range panjang dari jumlah index
#Dimana tiap nilai dari range akan diconvert menjadi 'Laki-laki'
nv_g1 = [] #nv_g1 singkatan untuk new value for gender 1
for i in range(len(ix_gender_1)):
  i = 'Laki-laki'
  nv_g1.append(i)

#Mengupdate nilai cell dari index yang sudah di-listing
df_surnas_copied.loc[ix_gender_1, 'JENIS KELAMIN'] = nv_g1

#Menampilkan perubahan (preview)
df_surnas_copied.loc[ix_gender_1, ['NO KUISIONER', 'JENIS KELAMIN']]

      NO KUISIONER JENIS KELAMIN
100            107     Laki-laki
102            109     Laki-laki
1010          1047     Laki-laki
1126          1169     Laki-laki

In [ ]:
#Mengecek (GENAP)(PEREMPUAN)

#Mengecek apakah ada nomor kuesioner genap yang berjenis kelamin laki-laki
gender_2 = df_surnas_copied[(df_surnas_copied['NO KUISIONER'] % 2 == 0) & (df_surnas_copied['JENIS KELAMIN'] == 'Laki-laki')]

gender_2.loc[:, ['NO KUISIONER', 'JENIS KELAMIN']]
#Ada 1 data yang tidak sesuai yakni nomor kuisioner: 71052

      NO KUISIONER JENIS KELAMIN
1288         71052     Laki-laki

In [ ]:
#Jika ingin MENGUBAH jenis kelaminnya menjadi perempuan

#Membuat daftar index dari sel yang ingin diubah
ix_gender_2 = [1288]

#Membuat iterasi untuk menampung range panjang dari jumlah index
#Dimana tiap nilai dari range akan diconvert menjadi 'Perempuan'
nv_g2 = [] #nv_g1 singkatan untuk new value for gender 2
for j in range(len(ix_gender_2)):
  j = 'Perempuan'
  nv_g2.append(j)

#Mengupdate nilai cell dari index yang sudah di-listing
df_surnas_copied.loc[ix_gender_2, 'JENIS KELAMIN'] = nv_g2

#Menampilkan perubahan (preview)
df_surnas_copied.loc[ix_gender_2, ['NO KUISIONER', 'JENIS KELAMIN']]

      NO KUISIONER JENIS KELAMIN
1288         71052     Perempuan

# B. Outlier Umur dan Coding Umur

In [ ]:
#Mencari Outlier umur, yakni umur yang berusia lebih dari 100 tahun
age = df_surnas_copied[df_surnas_copied['UMUR'] > 100]

#Menampilkan outlier umur
age.loc[:, ['NAMA RESPONDEN', 'UMUR']]

     NAMA RESPONDEN  UMUR
662     ALI ANSHORI   821
1046          NERRY   470

In [ ]:
#Mengubah outlier umur dengan ketentuan
    #Umur 821 menjadi 82, Umur 470 menjadi 47
ix_age = [662, 1046] #Melisting index outlier umur

nv_outlier_age = [82, 47] #Menginput nilai baru untuk outlier

#Mengupdate nilai cell dari index yang sudah di-listing
df_surnas_copied.loc[ix_age, 'UMUR'] = nv_outlier_age

#Menampilkan perubahan (preview)
df_surnas_copied.loc[ix_age, ['NAMA RESPONDEN', 'UMUR']]

     NAMA RESPONDEN  UMUR
662     ALI ANSHORI    82
1046          NERRY    47

Coding Milenial

In [ ]:
#Menambahkan kolom Coding Milenial dengan ketentuan:
  # Nilai 1 untuk <= 35, dan 2 unutk > 35
Coding_Milenial = df_surnas_copied['UMUR'].apply(lambda x: 1 if x <= 35 else 2)

#Dirun sekali untuk menghindari duplikasi
  #insert(index, nama, list of value)
df_surnas_copied.insert(27, "Coding_Milenial", Coding_Milenial, allow_duplicates=False)

#Preview kolom Coding_Milenial
df_surnas_copied.iloc[:, 20:30].sample(10)

,URBAN RURAL,LATITUDE,LONGITUDE,STATUS RESPONDEN,CODING PROVINSI,UMUR,CODING USIA,Coding_Milenial,CREATED AT,P1
579,1,-7.4161691,109.800732,PENGGANTI,13,66,6,2,07-06-2023 15:34:12,4
1170,1,-0.8566026,134.0694975,PENGGANTI,34,40,4,2,06-06-2023 14:24:45,4
859,2,-6.7764111,105.8585752,ASLI,16,39,4,2,07-06-2023 13:41:47,5
1227,1,0.3550179,101.1946054,ASLI,4,30,3,1,08-06-2023 09:47:35,2
1011,1,-0.8447098,119.9092639,ASLI,26,35,3,1,09-06-2023 13:02:42,3
1105,1,-2.5987821,140.6735797,ASLI,33,32,3,1,07-06-2023 10:52:05,2
794,1,-7.7795847,113.167953,ASLI,15,44,4,2,07-06-2023 16:06:53,5
550,1,.,.,ASLI,23,42,4,2,07-06-2023 20:10:44,2
305,1,-6.9061026,108.5008115,ASLI,22,37,4,2,07-06-2023 13:58:22,2
1297,1,.,.,ASLI,36,46,5,2,09-06-2023 19:32:36,2

# C. Coding Pulau

In [ ]:
#Menambahkan kolom Coding Pulau dengan ketentuan:
  #Mendefinisikan ketentuan area
area_1 = ['ACEH', 'SUMATERA BARAT', 'RIAU', 'JAMBI',
       'KEPULAUAN BANGKA BELITUNG', 'KEPULAUAN RIAU', 'SUMATERA UTARA',
       'SUMATERA SELATAN', 'BENGKULU', 'LAMPUNG']
area_2 = ['DKI JAKARTA', 'JAWA BARAT', 'BANTEN']
area_3 = ['DI YOGYAKARTA', 'JAWA TIMUR', 'JAWA TENGAH']

  #Membuat fungsi coding area
def area_coding (x):
  if x in area_1:
    return 1
  elif x in  area_2:
    return 2
  elif x in area_3:
    return 3
  else:
    return 4

#Melisting applied value untuk kolom Coding_Pulau
Coding_Pulau = df_surnas_copied['PROVINSI'].apply(lambda x: area_coding(x))

#Dirun sekali untuk menghindari duplikasi
  #insert(index, nama kolom, value)
# df_surnas_copied.insert(13, "Coding_Pulau", Coding_Pulau, allow_duplicates=False)

#Preview kolom Coding_Pulau
df_surnas_copied.iloc[:, 10:15].sample(10)

,KECAMATAN,KABUPATEN KOTA,PROVINSI,Coding_Pulau,JUMLAH RT DALAM KELURAHAN
1149,MERAUKE,MERAUKE,PAPUA SELATAN,4,13
799,KADEMANGAN,KOTA PROBOLINGGO,JAWA TIMUR,3,40
647,LABANG,BANGKALAN,JAWA TIMUR,3,4
1235,CIRUAS,KABUPATEN SERANG,BANTEN,2,16
225,KOTA AGUNG BARAT,TANGGAMUS,LAMPUNG,1,4
815,SUMBER WRINGIN,BONDOWOSO,JAWA TIMUR,3,39
424,WADO,SUMEDANG,JAWA BARAT,2,34
1002,TATAPAAN,MINAHASA SELATAN,SULAWESI UTARA,4,4
926,PONTIANAK SELATAN,PONTIANAK,KALIMANTAN BARAT,4,40
654,KETAPANG,SAMPANG,JAWA TIMUR,3,6

# D. MENGUBAH NILAI (.)

In [ ]:
#Melisting seluruh kolom
list_col = list(df_surnas_copied.columns)

list_col

['NO',
 'NAMA RESPONDEN',
 'HP RESPONDEN',
 'NO KUISIONER',
 'NAMA KEPALA KELUARGA',
 'JENIS KELAMIN',
 'ALAMAT',
 'RT',
 'RW',
 'KELURAHAN',
 'KECAMATAN',
 'KABUPATEN KOTA',
 'PROVINSI',
 'Coding_Pulau',
 'JUMLAH RT DALAM KELURAHAN',
 'JUMLAH KK DALAM RT',
 'WAKTU MULAI',
 'WAKTU SELESAI',
 'LAMA SURVEY',
 'TPD',
 'HP TPD',
 'URBAN RURAL',
 'LATITUDE',
 'LONGITUDE',
 'STATUS RESPONDEN',
 'CODING PROVINSI',
 'UMUR',
 'CODING USIA',
 'Coding_Milenial',
 'CREATED AT',
 'P1',
 'P2',
 'P3',
 'P3X',
 'P4',
 'P5',
 'P5X',
 'P6',
 'P6X',
 'P7',
 'P8',
 'P9',
 'P10',
 'P11',
 'P12',
 'P13',
 'P13X',
 'P14',
 'P14X',
 'P15',
 'P15X',
 'P16.1',
 'P16.2',
 'P16.3',
 'P17',
 'P18.1',
 'P18.1.1',
 'P18.2',
 'P18.2.2',
 'P18.3',
 'P18.3.3',
 'P18.4',
 'P18.4.4',
 'P18.5',
 'P18.5.5',
 'P18.6',
 'P18.6.6',
 'P18.7',
 'P18.7.7',
 'P18.8',
 'P18.8.8',
 'P18.9',
 'P18.9.9',
 'P18.10',
 'P18.10.10',
 'P18.11',
 'P18.11.11',
 'P18.12',
 'P18.12.12',
 'P18.13',
 'P18.13.13',
 'P18.14',
 'P18.14.14',
 'P18.15',
 'P18.15.15',
 'P18.16',
 'P18.16.16',
 'P19',
 'P20',
 'P21.1',
 'P21.1.1',
 'P22',
 'P23',
 'P23X',
 'P24.1',
 'P24.2',
 'P24.3',
 'P24.4',
 'P24.5',
 'P24.6',
 'P25.1',
 'P25.2',
 'P25.3',
 'P25.4',
 'P25.5',
 'P25.6',
 'P25.7',
 'P25.8',
 'P25.9',
 'P25.10',
 'P26.1',
 'P26.2',
 'P26.3',
 'P26.4',
 'P26.5',
 'P26.6',
 'P26.7',
 'P26.8',
 'P26.9',
 'P26.10',
 'P27',
 'P27X',
 'P28.1',
 'P28.2',
 'P28.3',
 'P28.4',
 'P28.5',
 'P28.6',
 'P28.7',
 'P28.8',
 'P28.9',
 'P28.10',
 'P29.1',
 'P29.1.1',
 'P30',
 'P31',
 'P32',
 'P33',
 'P34',
 'P35',
 'P36',
 'P36X',
 'P37',
 'P38',
 'P39',
 'P40',
 'P41',
 'P42',
 'P43',
 'P44',
 'P45',
 'P46',
 'P47',
 'P48',
 'P49',
 'P50',
 'P51',
 'P52',
 'P53',
 'P54',
 'P55',
 'P56',
 'P57',
 'P58',
 'P59',
 'P59X',
 'P60.1',
 'P60.2',
 'P60.3',
 'P61',
 'P62',
 'P63',
 'P64',
 'P65.1',
 'P65.2',
 'P65.3',
 'P65.4',
 'P66',
 'P67',
 'P68',
 'P69',
 'P70',
 'P71.1',
 'P71.2',
 'P71.3',
 'P72',
 'P73.1',
 'P73.2',
 'P73.3',
 'P73.4',
 'P73.5',
 'P73.6',
 'P73.7',
 'P73.8',
 'P73.9',
 'P73.10',
 'P73.11',
 'P73.12',
 'P73.13',
 'P74',
 'P75.1',
 'P75.2',
 'P75.3',
 'P75.4',
 'P76',
 'P76X',
 'P77',
 'P77X',
 'P78',
 'P79',
 'P79X',
 'P80',
 'P80X',
 'P81.1',
 'P81.2',
 'P81.3',
 'P81.4',
 'P81.5',
 'P82',
 'P83',
 'P84.1',
 'P84.2',
 'P84.3',
 'P85',
 'P86',
 'P86X',
 'P87',
 'P87X',
 'P88',
 'P89',
 'P90',
 'P90X',
 'P91',
 'P92',
 'P93',
 'P93X',
 'P94',
 'P94X',
 'P95',
 'P95X',
 'P96.1',
 'P96.2',
 'P96.3',
 'P96.4',
 'P97',
 'P98',
 'P98X',
 'P99',
 'P100',
 'P101',
 'P102',
 'P103',
 'P104',
 'P105']

In [ ]:
#Mmebuat iterasi untuk mengubah semua nilai di kolom x yang bernilai '.' menjadi ''
for col in list_col:
  df_surnas_copied[col].replace('.', '', inplace =True)

In [ ]:
#Preview perubahan nilai (.)
df_surnas_copied.loc[:, ['P5X', 'P6X', 'P13X', 'P14X', 'P18.2.2']].sample(5)

     P5X P6X P13X                                    P14X P18.2.2
1249
515                BANYAK KASUS BESAR YANG DITUTUP TUTUPI       5
226
948
712                                                             6

# E. CLEANING JAWABAN LAINNYA

List pertanyaan dengan jawaban lainnya:
3, 5, 6, 13, 14, 15, 23, 27, 36, 59, 76, 77, 79, 80, 86, 87, 90, 93, 94, 95, 98

Contoh Cleaning akan dilakukan untuk pertanyaan 3 (P3X)

In [ ]:
#Mengopi dataframe:
df_surnas_cleaned1 = df_surnas_copied.copy(deep=True)

In [ ]:
#Mengambil nilai unique dari jawaban lainnya:
df_surnas_cleaned1['P3X'].unique()

#Menghitung panjang nilai unik
# len(df_surnas_copied['P3X'].unique())
#Output: 68

array(['', 'BIAYA SEKOLAH', 'BIAYA SEKOLAH ,LISTRIK', 'ARISAN',
       'KEGIATAN KELUARGA BESAR (REWANG ATAU GOTONG ROYONG PESTA TETANGGA)',
       'BBM DAN KUOTA INTERNET', 'BIAYA SEKOLAH ANAK',
       'BIAYA ANAK SEKOLAH', 'BAYAR AIR', 'KONDANGAN', 'KONDNGAN',
       'TIDAK ADA', 'BIYAYA PENDIDIKAN', 'CICILAN MOTOR', 'CICILAN BANK',
       'ARISAN DAN UTANG', 'CICILAN HUTANG', 'PEMPES DAN SUSU ANAK',
       'GAYA HIDUP', 'PENGEMBANGAN BISNIS', 'CICILAN KE BANK AGRO',
       'CICILAN BANK EMOK', 'BIAYA KULIAH ANAK', 'ANGSURAN BANK',
       'BAYAR ARISAN', 'PUPUK',
       'UNDANGAN HAJATAN (DITANGGUNG ANAK KEBANYAKAN)', 'BELANJA',
       'SEKOLAH', 'PENDIDIKAN', 'AIR', 'STABIL', 'PENGOBATAN',
       'BANGUN RUMAH', 'SUSU', 'KEBUTUHAN AIR', 'KONDANGAN, DLL',
       'ANGSURAN', 'PENDIDIKAN SEKOLAH ANAK', 'CICILAN BANK KREDIT',
       'BIAYA PENDIDIKAN', 'CICILAN PINJAMAN UANG', 'SKINCARE',
       'PUPUK KOMPOS BAHAN TANI', 'ROKOK', 'PENDIDIKAN ANAK',
       'CICILAN SEPEDA MOTOR', 'UANG SAKU ANAN', 'JAJAN ANAK', 'CICILAN',
       'BIAYA PENDIDIKAN ANAK', 'TIDAK ADA YANG BERAT', 'AIR PDAM',
       'PUPUK , OBAT', 'PUPUK TANI',
       'PENGELUARAN TAK TERDUGA (KONDANGAN, SELAMATAN, DLL)',
       'ANGSURAN MOTOR', 'KULIAH ANAK', 'BAIK TIDAK ADA YG MEBEBANI',
       'KEBUTUHAN HARIAN DAN ANAK SEKOLAH', 'AIR PAM', 'CICILAN MOBIL',
       'CICILAN KENDARAAN', 'BAYAR CICILAN TANAH',
       'PUPUK DAN OBAT2AN TANAMAN', 'CICILAN UNTUK USAHA KEBUN DI BANK',
       'KEPERLUAN SEKOLAH', 'ROKOK SAMA MAKAN'], dtype=object)

In [ ]:
#membuat list yang menampung array dari kolom P3X
list_p3x = list(df_surnas_cleaned1['P3X'].unique())
# list_p3x
# len(list_p3x)

In [ ]:
#Membuat listing untuk kategori yang sama:
pendidikan = ['BIAYA SEKOLAH', 'BIAYA SEKOLAH ,LISTRIK', 'BIAYA SEKOLAH ANAK','BIAYA ANAK SEKOLAH', 'BIYAYA PENDIDIKAN',
              'BIAYA KULIAH ANAK', 'SEKOLAH', 'PENDIDIKAN', 'PENDIDIKAN SEKOLAH ANAK', 'BIAYA PENDIDIKAN', 'PENDIDIKAN ANAK',
              'UANG SAKU ANAN', 'JAJAN ANAK','BIAYA PENDIDIKAN ANAK', 'KULIAH ANAK',  'KEPERLUAN SEKOLAH']

cicilan_beban_produktif = ['CICILAN MOTOR', 'CICILAN BANK','CICILAN UNTUK USAHA KEBUN DI BANK','CICILAN HUTANG',
                           'PENGEMBANGAN BISNIS', 'CICILAN KE BANK AGRO', 'CICILAN BANK EMOK', 'ANGSURAN BANK',
                           'PUPUK', 'BANGUN RUMAH', 'ANGSURAN', 'CICILAN BANK KREDIT', 'CICILAN PINJAMAN UANG',
                           'PUPUK KOMPOS BAHAN TANI',  'CICILAN SEPEDA MOTOR', 'CICILAN',  'PUPUK , OBAT', 'PUPUK TANI',
                            'ANGSURAN MOTOR', 'CICILAN MOBIL', 'CICILAN KENDARAAN', 'BAYAR CICILAN TANAH','PUPUK DAN OBAT2AN TANAMAN' ]

rekreasi_arisan = ['ARISAN','KEGIATAN KELUARGA BESAR (REWANG ATAU GOTONG ROYONG PESTA TETANGGA)','SKINCARE', 'ROKOK', 'ROKOK SAMA MAKAN',
                   'KONDANGAN', 'KONDNGAN', 'ARISAN DAN UTANG', 'GAYA HIDUP', 'BAYAR ARISAN','UNDANGAN HAJATAN (DITANGGUNG ANAK KEBANYAKAN)',
                   'KONDANGAN, DLL']

air = ['AIR PAM', 'BAYAR AIR', 'AIR', 'KEBUTUHAN AIR','AIR PDAM' ]

kesehatan = ['PENGOBATAN']

transportasi_1 = ['BBM DAN KUOTA INTERNET']

bahan_pokok_3 = ['BELANJA','KEBUTUHAN HARIAN DAN ANAK SEKOLAH']

lainnya = ['TIDAK ADA', 'PEMPES DAN SUSU ANAK','STABIL', 'SUSU', 'TIDAK ADA YANG BERAT', 'PENGELUARAN TAK TERDUGA (KONDANGAN, SELAMATAN, DLL)',
            'BAIK TIDAK ADA YG MEBEBANI', '']

#Menghitung jumlah input
n_lainnya = (len(pendidikan) + len(cicilan_beban_produktif) + len(rekreasi_arisan)
              + len(air) + len(kesehatan) + len(transportasi_1) + len(bahan_pokok_3) + len(lainnya))
#Output= 68 [Semua nilai array sudah terinput]

In [ ]:
mapping = {}

for i in list_p3x:
  if i in pendidikan:
    map_1 = {i: "Pendidikan"}
    mapping.update(map_1)
  if i in cicilan_beban_produktif:
    map_2 = {i: "Cicilan/Beban Produktif"}
    mapping.update(map_2)
  if i in rekreasi_arisan:
    map_3 = {i : "Rekreasi/Arisan"}
    mapping.update(map_3)
  if i in air:
    map_4 = {i : "Air"}
    mapping.update(map_4)
  if i in kesehatan:
    map_5 = {i : "Kesehatan"}
    mapping.update(map_5)
  if i in transportasi_1:
    map_6 = {i : "Transportasi"}
    mapping.update(map_6)
  if i in bahan_pokok_3:
    map_7 = {i : "Bahan Pokok"}
    mapping.update(map_7)
  if i in lainnya:
    map_8 = {i : "Lainnya"}
    mapping.update(map_8)

In [ ]:
#Melakukan mapping unutk mengganti nilai array pada kolom P3X menjadi nilai yang dikoding sesuai kategori
df_surnas_cleaned1['P3X'] = df_surnas_cleaned1['P3X'].map(lambda x: mapping.get(x,x))

In [ ]:
#Preview nilai unik setelah kategorisasi nilai lainnya
df_surnas_cleaned1['P3X'].unique()

array(['Lainnya', 'Pendidikan', 'Rekreasi/Arisan', 'Transportasi', 'Air',
       'Cicilan/Beban Produktif', 'Bahan Pokok', 'Kesehatan'],
      dtype=object)

In [ ]:
df_surnas_cleaned1.loc[:, ['P3X','P4']].sample(10)

                          P3X  P4
1177                  Lainnya   3
392                Pendidikan   2
1253                  Lainnya   1
325   Cicilan/Beban Produktif   3
594                   Lainnya   2
771                   Lainnya   3
1264                  Lainnya   1
699                Pendidikan   2
33                    Lainnya   2
37                    Lainnya   2

# F. JAWABAN TERBUKA

Pertanyaan-pertanyaan dengan jawaban tebruka: 7, 8, 22, 33, 34, 35

Contoh akan dilakukan pada pertanyaan 7 (P7)

In [ ]:
# Membuat list nilai unik dari P7
list_p7 = list(df_surnas_cleaned1['P7'].unique())

#Mengurutkan nama
list_p7.sort()

list_p7

['-',
 '88',
 'AANIAANIESAANIAANIES BBASBBASWEBBASBBASWEDABBASBBASWEBBASBBASWEDAN',
 'AGUS HARIMURTI',
 'AGUS HARIMURTI YUDHOYONO',
 'AHOK',
 'AHOK(BASUKI CAHAYA PURNAMA)',
 'AIRLANGGA HARTANTO',
 'AIRLANGGA HARTARTO',
 'AMIN RAIS',
 'ANDIKA',
 'ANDIKA PERKASA',
 'ANIES',
 'ANIES BASWEDAN',
 'ANIS',
 'ANIS BASWEDAH',
 'ANIS BASWEDAN',
 'ANIS BASWESAN',
 'ANIS RASYID BASWEDAN',
 'ARI TANI',
 'BASUKI TJAJHJA AHOK',
 'BEELUM TAHU',
 'BELOM ADA',
 'BELOM TAHU',
 'BELOM TAHU CALONNYA',
 'BELOM TAU',
 'BELUM',
 'BELUM ADA',
 'BELUM ADA BAYANGAN',
 'BELUM ADA CALON',
 'BELUM ADA KANDIDAT',
 'BELUM ADA KEPUTUSAN',
 'BELUM ADA NAMA',
 'BELUM ADA PANDANGAN',
 'BELUM ADA PILIHAN',
 'BELUM ADA YANG KEBAYANG',
 'BELUM ADA YANG PAS',
 'BELUM BISA MEMILIH',
 'BELUM BISA MEMUTUSKAN',
 'BELUM BISA MENJAWAB',
 'BELUM DIKETAHUI CALONNYA',
 'BELUM INGIN MENJAWAB',
 'BELUM KELIHATAN',
 'BELUM MEMASTIKAN',
 'BELUM MEMUTUS KAN',
 'BELUM MEMUTUSKAN',
 'BELUM MENENTUKAN',
 'BELUM MENENTUKAN PILIHAN',
 'BELUM MENJAWAB',
 'BELUM MENNTUKAN PILIHAN',
 'BELUM MENTUKAN PILIHAN',
 'BELUM NEMUTUSKAN',
 'BELUM NGIKUTIN',
 'BELUM PASTI',
 'BELUM PASTI MENURUT PASANGAN',
 'BELUM TAHU',
 'BELUM TAHU CALON',
 'BELUM TAHU CALONNYA',
 'BELUM TAHU CALONYA',
 'BELUM TAHU NAMA CALON',
 'BELUM TAU',
 'BELUM TAU CALON',
 'BELUM TAU CALONNYA',
 'BELUMTAU',
 'BLM ADA',
 'BLM ADA PILIHAN',
 'BLM BISA MENJAWAB',
 'BLM BISA MENJELASKAN',
 'BLM MILIH',
 'BLM TAU',
 'ERICK THOHIR',
 'ERIK THOHIR',
 'ERIK TOHIR',
 'GA ADA',
 'GANJAR',
 'GANJAR P',
 'GANJAR PRANOMO',
 'GANJAR PRANOWO',
 'GENJAR PRANOWO',
 'GIBRAN',
 'GIBRAN RAKABUMING',
 'GIBRAN RAKABUMING RAKA',
 'GOLPUT',
 'HARI TANOE',
 'HJ. NURBAETI',
 'JOKI WIDODO',
 'JOKO WIDODO',
 'JOKO WIDODO DAN GANJAR PRANOWO',
 'JOKOWI',
 'JOKOWI DODO',
 'JOKOWIDODO',
 'JUSUF KALLA',
 'KITA LIAT DARI SIFAT PEMIMPINYA DULU NANTI',
 'KONDISIONAL',
 'KURANG TAHU',
 'KURANG TAU',
 'MAHFUD',
 'MAHFUD MD',
 'MAHMUD',
 'MASIH PAK JOKOWI',
 'MAU YANG AEPERTI PAK JOKOWI',
 'MBOTEN NGERTOS',
 'MEGAWATI',
 'MEMILIH SUAMI',
 'MENOLAK MENJAWAB',
 'MUAIMIN ISKANDAR',
 'MUHAIMIN ISKANDAR',
 'PAK PRABOWO',
 'PEABOWO',
 'PRABOWO',
 'PRABOWO S',
 'PRABOWO SUBIABTO',
 'PRABOWO SUBIANTO',
 'PRANOWO',
 'PROBOWO',
 'PROBOWO SUBIANTO',
 'PUAN MAHARANI',
 'RAHASIA',
 'RIDWAN KAMIL',
 'RIZIK SIHAP',
 'SANDIAGA UNO',
 'SURYA PALOH',
 'TIDAK ADA',
 'TIDAK ADA CALON',
 'TIDAK ADA PANDANGAN',
 'TIDAK ADA PILIHAN',
 'TIDAK BISA MENJAWAB',
 'TIDAK MAU MENYEBUTKAN',
 'TIDAK MENJAWAB',
 'TIDAK PAHAM',
 'TIDAK TAHU',
 'TIDAK TAHU / BELUM MENENTUKAN',
 'TIDAK TAHU CALONNYA',
 'TIDAK TAHU NAMA TOKOH',
 'TIDAK TAU',
 'TIDAK TAU CALONNYA',
 'TT',
 'TUDAK TAHU',
 'YANG BISA MENSEJAHTERAKAN BURUH',
 'YANG KAYAK PAK JOKOWI',
 'YANG TERBAIK']

In [ ]:
#List kategori
anies_baswedan = ['AANIAANIESAANIAANIES BBASBBASWEBBASBBASWEDABBASBBASWEBBASBBASWEDAN', 'ANIS BASWESAN',
                  'ANIS BASWEDAH','ANIES BASWEDAN', 'ANIS BASWEDAN', 'ANIS','ANIES', 'ANIS RASYID BASWEDAN']
prabowo_subianto = ['PROBOWO', 'PEABOWO', 'PRABOWO S', 'PAK PRABOWO','PROBOWO SUBIANTO','PRABOWO','PRABOWO SUBIANTO','PRABOWO SUBIABTO']
ganjar_pranowo = ['PRANOWO', 'GANJAR PRANOMO', 'GANJAR P', 'GANJAR', 'GENJAR PRANOWO', 'GANJAR PRANOWO']
basuki_tp = ['AHOK', 'AHOK(BASUKI CAHAYA PURNAMA)',  'BASUKI TJAJHJA AHOK']
mahfud_md = ['MAHMUD', 'MAHFUD', 'MAHFUD MD']
jokowi_dodo = ['JOKI WIDODO','MASIH PAK JOKOWI', 'JOKO WIDODO', 'JOKOWI', 'JOKI WIDODO', 'JOKOWI DODO', 'JOKOWIDODO']
erick_thohir = ['ERICK THOHIR', 'ERIK THOHIR',  'ERIK TOHIR']
gibran = ['GIBRAN', 'GIBRAN RAKABUMING RAKA', 'GIBRAN RAKABUMING']
ahy = ['AGUS HARIMURTI YUDHOYONO' 'AGUS HARIMURTI YUDHOYONO', 'AGUS HARIMURTI YUDHOYONO']
andika_perkasa = ['ANDIKA', 'ANDIKA PERKASA']
puan_maharani = ['PUAN MAHARANI']
jusuf_kalla = ['JUSUF KALLA']
ari_tani =['ARI TANI']
sandi_uno = ['SANDIAGA UNO']
muhaimin = ['MUHAIMIN ISKANDAR']
hari_tanoe = ['HARI TANOE']
amin_rais = ['AMIN RAIS']
megawati = ['MEGAWATI', 'MEGAWATI']
airlangga = ['AIRLANGGA HARTARTO']
rizieq_shihab = ['RIZIK SIHAP']
ridwan = ['RIDWAN KAMIL']
suryaPaloh = ['SURYA PALOH']

In [ ]:
mapping_p7 = {}
for i in list_p7:
  if i in anies_baswedan:
    anies = {i: "ANIES BASWEDAN"}
    mapping_p7.update(anies)
  elif i in prabowo_subianto:
    prabowo = {i :"PRABOWO SUBIANTO"}
    mapping_p7.update(prabowo)
  elif i in ganjar_pranowo:
    ganjar = {i :"GANJAR PRANOWO"}
    mapping_p7.update(ganjar)
  elif i in basuki_tp:
    basuki = {i : "BASUKI TJAHAYA"}
    mapping_p7.update(basuki)
  elif i in mahfud_md:
    mahfud = {i : "MAHFUD MD"}
    mapping_p7.update(mahfud)
  elif i in jokowi_dodo:
    jokowi = {i : "JOKOWI DODO"}
    mapping_p7.update(jokowi)
  elif i in erick_thohir:
    erick = {i : "ERICK THOHIR"}
    mapping_p7.update(erick)
  elif i in gibran:
    gibran_raka = {i : "GIBRAN RAKABUMING RAKA"}
    mapping_p7.update(gibran_raka)
  elif i in ahy:
    agus_hari = {i : "AGUS HARIMURTI YUDHOYONO"}
    mapping_p7.update(agus_hari)
  elif i in andika_perkasa:
    andika = {i : "ANDIKA PERKASA"}
    mapping_p7.update(andika)
  elif i in puan_maharani:
    puan = {i : "PUAN MAHARANI"}
    mapping_p7.update(puan)
  elif i in jusuf_kalla:
    jk = {i : "JUSUF KALLA"}
    mapping_p7.update(jk)
  elif i in ari_tani:
    ari = {i : "ARI TANI"}
    mapping_p7.update(ari)
  elif i in sandi_uno:
    sandi = {i : "SANDIAGA UNO"}
    mapping_p7.update(sandi)
  elif i in muhaimin:
    muhaimin = {i : "MUHAIMIN ISKANDAR"}
    mapping_p7.update(jk)
  elif i in hari_tanoe:
    hari = {i : "HARY TANOE"}
    mapping_p7.update(hari)
  elif i in amin_rais:
    amin = {i : "AMIN RAIS"}
    mapping_p7.update(amin)
  elif i in megawati:
    megawati = {i : "MEGAWATI"}
    mapping_p7.update(megawati)
  elif i in airlangga:
    airlangga = {i : "AIRLANGGA HARTARTO"}
    mapping_p7.update(airlangga)
  elif i in ridwan:
    ridwan = {i : "RIDWAN KAMIL"}
    mapping_p7.update(ridwan)
  elif i in rizieq_shihab:
    rizieq = {i : "RIZIEQ SHIHAB"}
    mapping_p7.update(rizieq)
  elif i in suryaPaloh:
    surya = {i : "SURYA PALOH"}
    mapping_p7.update(surya)
  else:
    lainnya = {i: "BELUM MEMUTUSKAN/TIDAK MENJAWAB"}
    mapping_p7.update(lainnya)

# mapping_p7

In [ ]:
#Melakukan mapping untuk mengganti nilai array pada kolom P7 menjadi nilai yang dikoding sesuai kategori
df_surnas_cleaned1['P7'] = df_surnas_cleaned1['P7'].map(lambda x: mapping_p7.get(x,x))

In [ ]:
#Preview nilai unik pada nilai kolom P7
df_surnas_cleaned1['P7'].unique()

df_surnas_cleaned1.loc[:, ['P7', 'P8']]

                    P7                        P8
0       ANIES BASWEDAN  AGUS HARIMURTI YUDHOYONO
1       ANIES BASWEDAN              RIDWAN KAMIL
2       ANIES BASWEDAN  AGUS HARIMURTI YUDHOYONO
3     PRABOWO SUBIANTO                 MAHFUD MD
4       ANIES BASWEDAN  AGUS HARIMURTI YUDHOYONO
...                ...                       ...
1298  PRABOWO SUBIANTO              RIDWAN KAMIL
1299    GANJAR PRANOWO             TIDAK DIJAWAB
1300    GANJAR PRANOWO               ERICK TOHIR
1301    ANIES BASWEDAN   SANDIAGA SALAHHUDIN UNO
1302    GANJAR PRANOWO              RIDWAN KAMIL

[1303 rows x 2 columns]

In [ ]:
#[[KODE UNTUK MEMBUAT LIST, MENGECEK PANJANG LIST DARI SUATU KOLOM BERDASARKAN NILAI UNIK]]
# list_p33 = list(df_surnas_cleaned1['P80X'].unique())
# list_p33.sort()

# len(list_p33)
# list_p33

# G. PERTANYAAN BRANCHING

Sampel contoh:
Jawaban untuk P4: (1-2), P5: (2-11) |
Jawaban untuk P4: (3-6), P5: 1

In [ ]:
#Membuat kondisi dimana P4 bernilai kecil dari 2, memiliki jawaban P5 selain 2-11 atau bernilai = 1
branching_1 = df_surnas_cleaned1[(df_surnas_cleaned1['P4'] <=2) & (df_surnas_cleaned1['P5'] == 1)]

#Preview dataframe
branching_1.loc[:, ['P4', 'P5']]
#Ambil nilai index untuk melakukan cleaning di dataframe awal
#Nilai index adalah 156, dan 1216
#Nilai 1 pada jawaban kolom 5, akan diubah nilainya mnejadi 11 (Tidak Tahu/Tidak Jawab)

      P4  P5
26     2   1
27     2   1
28     2   1
156    1   1
530    2   1
533    2   1
805    2   1
1216   1   1

In [ ]:
#Membuat daftar index dari sel yang ingin diubah
ix_branching_1 = [26, 27, 28, 156, 530, 533, 805, 1216]

#Membuat iterasi untuk menampung range panjang dari jumlah index
#Dimana tiap nilai dari range akan diconvert menjadi 11
nv_branching_1 = [] #nv_g1 singkatan untuk new value for branching 1
for b in range(len(ix_branching_1)):
  b = 11
  nv_branching_1.append(b)

#Mengupdate nilai cell dari index yang sudah di-listing
df_surnas_cleaned1.loc[ix_branching_1, 'P5'] = nv_branching_1

#Menampilkan perubahan (preview)
df_surnas_cleaned1.loc[ix_branching_1, ['P4', 'P5']]

      P4  P5
26     2  11
27     2  11
28     2  11
156    1  11
530    2  11
533    2  11
805    2  11
1216   1  11